### ISSUE TITLE
xur when?

### ISSUE THREAD

**Issue by G3NSVRV** [Aioros/destiny-reminders#11]
xur when? I saw other sites that prints the info of where is xur and what is selling, like wtfix and charlemagne, that data could be gattered via api, and would be awesome if I can receive a notification when XUR sells something that I need like in this season the Aeon Gauntlets.

**Comment by Aioros** [comment]
Well, you're absolutely right. I intended to add Xûr right after Banshee and Spider, but then other issues popped up. I have less time than I'd like at the moment, but I'll try to prioritize this.

**Comment by G3NSVRV** [comment]
thanks, if you need any help you can ping me. I will try by my side how to query that data.

**Comment by Aioros** [comment]
Just deployed the updated version with Xûr support added. I'm going to close this issue, but feel free to open a new one if there's any trouble with the new vendor.

**Comment by G3NSVRV** [comment]
wow!! you are awesome m8, thanks a lot!!! I put my first notifications ☺️
