### ISSUE TITLE
Legend/master lost sector reminder

### ISSUE THREAD

**Issue by fmajestic** [Aioros/destiny-reminders#5]
Will you be adding a reminder for legend and master lost sector rewards?

Something like "when Legend reward is Arms" or "when Master reward is Chest"

**Comment by Aioros** [comment]
Yes, it's the main thing I'm working on and it's almost ready. Unfortunately, I have to solve another urgent issue first, but after that, it's definitely going to be part of the site.

**Comment by Aioros** [comment]
Just deployed the update, Lost Sectors are now supported. I'll close this enhancement issue and I'll keep an eye for any bug/issue that might pop up.
