### ISSUE TITLE
can't sign in

### ISSUE THREAD

**Issue by treflar** [Aioros/destiny-reminders#8]
I'm getting this "There was an error retrieving your Destiny membership information. Make sure you have an active Destiny account." bungie.net shows that i approved destiny reminders permission 11 days ago.

**Comment by Aioros** [comment]
I'll look into it. Do you mind telling me your PSN/gamertag?

**Comment by treflar** [comment]
sure, spiniestgnu40 on xbox

**Comment by Aioros** [comment]
Could it be that you don't have your xbox account linked to your Bungie.net profile?

**Comment by treflar** [comment]
bungie shows I'm linked
![Screen Shot 2021-01-17 at 1 06 53 PM](https://user-images.githubusercontent.com/62850073/104853222-04f68b00-58c5-11eb-854a-eb02edf5b085.png)

**Comment by Aioros** [comment]
Hey, sorry to say I'm still investigating at the moment. In the meantime I'm afraid I'll have to go with a couple of apparently stupid questions:

1. are you sure you don't have another bungie.net account that you might be logging in with by mistake? 
2. are you able to log in to other apps and see your characters with the same account?

**Comment by Aioros** [comment]
I think I found and fixed the issue, I wasn't considering that a linked account could be hidden from the public. Added the correct credentials for the request and it should work now. Let me know if you're able to log in now.

**Comment by treflar** [comment]
Success! Logged in and set a reminder first try, Thank-you.

**Comment by Aioros** [comment]
That's great! Sorry it took a while to fix, and thank you for your help.
